-- Estrutura da tabela reparosb2b para armazenar dados do arquivo BDs.xlsx
-- Todos os campos são do tipo texto para evitar problemas de formatação

CREATE TABLE IF NOT EXISTS reparosb2b (
    id INT AUTO_INCREMENT PRIMARY KEY,
    bd TEXT UNIQUE NOT NULL COMMENT 'Identificador único do BD (chave para evitar duplicação)',
    id_circuito TEXT COMMENT 'ID do circuito',
    bd_ant TEXT COMMENT 'BD antigo',
    lp_15 TEXT COMMENT 'LP 15',
    designador_lp_13 TEXT COMMENT 'Designador LP 13',
    id_comercial TEXT COMMENT 'ID comercial',
    data_abertura TEXT COMMENT 'Data de abertura',
    data_reparo TEXT COMMENT 'Data do reparo',
    data_encerramento TEXT COMMENT 'Data de encerramento',
    data_baixa TEXT COMMENT 'Data de baixa',
    last_update TEXT COMMENT 'Última atualização',
    kpi TEXT COMMENT 'KPI',
    kpi_acesso TEXT COMMENT 'KPI acesso',
    tipo_acesso TEXT COMMENT 'Tipo de acesso',
    origem TEXT COMMENT 'Origem',
    sistema_origem TEXT COMMENT 'Sistema de origem',
    cod_grupo TEXT COMMENT 'Código do grupo',
    grupo_economico TEXT COMMENT 'Grupo econômico',
    bd_raiz TEXT COMMENT 'BD raiz',
    status_codigo TEXT COMMENT 'Código do status',
    status_nome TEXT COMMENT 'Nome do status',
    procedencia TEXT COMMENT 'Procedência',
    reclamacao TEXT COMMENT 'Reclamação',
    segmento_sistema TEXT COMMENT 'Segmento do sistema',
    segmento_v3 TEXT COMMENT 'Segmento V3',
    segmento_novo TEXT COMMENT 'Segmento novo',
    segmento_vivo_corp TEXT COMMENT 'Segmento Vivo Corp',
    projeto TEXT COMMENT 'Projeto',
    cliente_nome TEXT COMMENT 'Nome do cliente',
    cnpj TEXT COMMENT 'CNPJ',
    cnpj_raiz TEXT COMMENT 'CNPJ raiz',
    endereco TEXT COMMENT 'Endereço',
    localidade_codigo TEXT COMMENT 'Código da localidade',
    area_codigo TEXT COMMENT 'Código da área',
    escritorio_codigo TEXT COMMENT 'Código do escritório',
    cidade TEXT COMMENT 'Cidade',
    uf TEXT COMMENT 'Unidade federativa',
    cluster TEXT COMMENT 'Cluster',
    regional TEXT COMMENT 'Regional',
    regional_vivo TEXT COMMENT 'Regional Vivo',
    lp_operadora TEXT COMMENT 'LP operadora',
    servico_cpcc_nome TEXT COMMENT 'Nome do serviço CPCC',
    velocidade TEXT COMMENT 'Velocidade',
    velocidade_kbps TEXT COMMENT 'Velocidade em Kbps',
    produto_nome TEXT COMMENT 'Nome do produto',
    familia_produto TEXT COMMENT 'Família do produto',
    baixa_n1_codigo TEXT COMMENT 'Código da baixa N1',
    baixa_n2_codigo TEXT COMMENT 'Código da baixa N2',
    baixa_n3_codigo TEXT COMMENT 'Código da baixa N3',
    baixa_n4_codigo TEXT COMMENT 'Código da baixa N4',
    baixa_n5_codigo TEXT COMMENT 'Código da baixa N5',
    baixa_n1_nome TEXT COMMENT 'Nome da baixa N1',
    baixa_n2_nome TEXT COMMENT 'Nome da baixa N2',
    baixa_n3_nome TEXT COMMENT 'Nome da baixa N3',
    baixa_n4_nome TEXT COMMENT 'Nome da baixa N4',
    baixa_n5_nome TEXT COMMENT 'Nome da baixa N5',
    resumo_intragov TEXT COMMENT 'Resumo intragov',
    intragov_sigla TEXT COMMENT 'Sigla intragov',
    intragov_codigo TEXT COMMENT 'Código intragov',
    sla_horas TEXT COMMENT 'SLA em horas',
    grupo TEXT COMMENT 'Grupo',
    grupo_novo TEXT COMMENT 'Grupo novo',
    foco_acoes TEXT COMMENT 'Foco das ações',
    foco_novo TEXT COMMENT 'Foco novo',
    grupo_baixa_codigo TEXT COMMENT 'Código do grupo de baixa',
    grupo_abertura TEXT COMMENT 'Grupo de abertura',
    usuario_abertura TEXT COMMENT 'Usuário de abertura',
    grupo_baixa TEXT COMMENT 'Grupo de baixa',
    usuario_baixa TEXT COMMENT 'Usuário de baixa',
    grupo_responsavel TEXT COMMENT 'Grupo responsável',
    operadora TEXT COMMENT 'Operadora',
    tipo_operadora TEXT COMMENT 'Tipo de operadora',
    tmr TEXT COMMENT 'TMR (Tempo Médio de Reparo)',
    tmr_sem_parada TEXT COMMENT 'TMR sem parada',
    tempo_parada TEXT COMMENT 'Tempo de parada',
    decorrido_sem_parada TEXT COMMENT 'Decorrido sem parada',
    prazo TEXT COMMENT 'Prazo',
    reincidencia_30d TEXT COMMENT 'Reincidência 30 dias',
    reincidencia_tipo TEXT COMMENT 'Tipo de reincidência',
    originou_reinc TEXT COMMENT 'Originou reincidência',
    prox_reinc TEXT COMMENT 'Próxima reincidência',
    horario_func_inicio TEXT COMMENT 'Horário de funcionamento início',
    horario_func_fim TEXT COMMENT 'Horário de funcionamento fim',
    R30_Tratativas TEXT COMMENT 'Tratativas R30',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT 'Data de criação do registro',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Data da última atualização'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Tabela para armazenar dados de reparos B2B provenientes do arquivo BDs.xlsx';

-- Índices para otimizar consultas comuns
CREATE INDEX idx_bd ON reparosb2b(bd);
CREATE INDEX idx_data_abertura ON reparosb2b(data_abertura);
CREATE INDEX idx_data_encerramento ON reparosb2b(data_encerramento);
CREATE INDEX idx_cluster ON reparosb2b(cluster);
CREATE INDEX idx_regional ON reparosb2b(regional);
CREATE INDEX idx_procedencia ON reparosb2b(procedencia);