-- Script para criar a tabela reparos_b2b_tmr no banco MariaDB

CREATE TABLE IF NOT EXISTS reparos_b2b_tmr (
    id INT AUTO_INCREMENT PRIMARY KEY,
    mes_inicio VARCHAR(20),
    vdi_codigo INT,
    tqi_codigo INT,
    tqi_raiz INT,
    id_circuito VARCHAR(100),
    status_vida VARCHAR(20),
    status_reparo VARCHAR(20),
    procedencia VARCHAR(20),
    produto VARCHAR(20),
    origem VARCHAR(10),
    cidade VARCHAR(100),
    uf VARCHAR(2),
    estado VARCHAR(100),
    endereco VARCHAR(255),
    tipo_cidade VARCHAR(20),
    regional VARCHAR(50),
    nom_cluster VARCHAR(50),
    nome_cliente VARCHAR(255),
    grp_codigo INT,
    grp_nome VARCHAR(255),
    grupo_baixa VARCHAR(255),
    tqi_diagnostico INT,
    dgn_descricao TEXT,
    tqi_abertura DATETIME,
    tqi_encerramento DATETIME,
    vdi_data_inicio DATETIME,
    vdi_data_fim DATETIME,
    tmr_total DECIMAL(10, 2),
    data_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_tqi_codigo (tqi_codigo),
    INDEX idx_vdi_codigo (vdi_codigo),
    INDEX idx_data_inicio (vdi_data_inicio),
    INDEX idx_cluster (nom_cluster),
    INDEX idx_regional (regional),
    INDEX idx_data_registro (data_registro)
);